name: Release package
on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Install pnpm
        run: corepack enable
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: production=true pnpm build
      - name: Check
        run: pnpm check
      - name: Create PR or publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run ci:version
          publish: pnpm run ci:publish
          title: 'chore: release package'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
